babelDomains = {
  ALL: 'All',
  ANIMALS: 'Animals',
  ART_ARCHITECTURE_AND_ARCHAEOLOGY: 'Art, artchitecture and archaelogy',
  BIOLOGY: 'Biology',
  BUSINESS_ECONOMICS_AND_FINANCE : 'Business, economics and finance',
  CHEMISTRY_AND_MINERALOGY : 'Chemistry and mineralogy',
  COMPUTING : 'Computing',
  CULTURE_AND_SOCIETY : 'Culure and society',
  EDUCATION : 'Education',
  ENGINEERING_AND_TECHNOLOGY : 'Engineering and technology',
  FARMING : 'Farming',
  FOOD_AND_DRINK : 'Food and drink',
  GAMES_AND_VIDEO_GAMES : 'Games and videogames',
  GEOGRAPHY_AND_PLACES : 'Geography and places',
  GEOLOGY_AND_GEOPHYSICS : 'Geology and geophysics',
  HEALTH_AND_MEDICINE : 'Health and medicine',
  HERALDRY_HONORS_AND_VEXILLOLOGY : 'Heraldry, honors and vexillology',
  HISTORY : 'History',
  LANGUAGE_AND_LINGUISTICS : 'Language and linguistics',
  LAW_AND_CRIME : 'Law and crime',
  LITERATURE_AND_THEATRE : 'Literature and theatre',
  MATHEMATICS : 'Mathematics',
  MEDIA : 'Media',
  METEOROLOGY : 'Meteorology',
  MUSIC : 'Musica',
  NUMISMATICS_AND_CURRENCIES : 'Numismatics and currencies',
  PHILOSOPHY_AND_PSYCHOLOGY : 'Philosophy and psychology',
  PHYSICS_AND_ASTRONOMY : 'Physics and astronomy',
  POLITICS_AND_GOVERNMENT : 'Politics and government',
  RELIGION_MYSTICISM_AND_MYTHOLOGY : 'Religion, mysticism and mythology',
  ROYALTY_AND_NOBILITY : 'Royalty and nobility',
  SPORT_AND_RECREATION : 'Sport and recreation',
  TEXTILE_AND_CLOTHING : 'Textile and clothing',
  TRANSPORT_AND_TRAVEL : 'Transport and travel',
  WARFARE_AND_DEFENSE : 'Warfare and defense'
};
